//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclestreets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyclestreets.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleStreets.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balanced route.
        /// </summary>
        public static string BalancedRoute {
            get {
                return ResourceManager.GetString("BalancedRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 avoided.
        /// </summary>
        public static string CO2Avoided {
            get {
                return ResourceManager.GetString("CO2Avoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not calculate route.
        /// </summary>
        public static string CouldNotCalculateRoute {
            get {
                return ResourceManager.GetString("CouldNotCalculateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor.
        /// </summary>
        public static string Cursor {
            get {
                return ResourceManager.GetString("Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Route Type.
        /// </summary>
        public static string DefaultRouteType {
            get {
                return ResourceManager.GetString("DefaultRouteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions.
        /// </summary>
        public static string directions {
            get {
                return ResourceManager.GetString("directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Feedback.
        /// </summary>
        public static string DirectionsResults_DirectionsResults_Route_Feedback {
            get {
                return ResourceManager.GetString("DirectionsResults_DirectionsResults_Route_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DirectionsResults_DirectionsResults_Save {
            get {
                return ResourceManager.GetString("DirectionsResults_DirectionsResults_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string DirectionsResults_DirectionsResults_Share {
            get {
                return ResourceManager.GetString("DirectionsResults_DirectionsResults_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1} &amp;#xA;Continue for {2} m.
        /// </summary>
        public static string DirectionText {
            get {
                return ResourceManager.GetString("DirectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fastest route.
        /// </summary>
        public static string FastestRoute {
            get {
                return ResourceManager.GetString("FastestRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some comments before pressing submit..
        /// </summary>
        public static string Feedback_enterComments {
            get {
                return ResourceManager.GetString("Feedback_enterComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Feedback.
        /// </summary>
        public static string Feedback_feedbackTypes_App_Feedback {
            get {
                return ResourceManager.GetString("Feedback_feedbackTypes_App_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report.
        /// </summary>
        public static string Feedback_feedbackTypes_Bug_Report {
            get {
                return ResourceManager.GetString("Feedback_feedbackTypes_Bug_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Feedback_feedbackTypes_Other {
            get {
                return ResourceManager.GetString("Feedback_feedbackTypes_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Feedback.
        /// </summary>
        public static string Feedback_feedbackTypes_Route_Feedback {
            get {
                return ResourceManager.GetString("Feedback_feedbackTypes_Route_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments.
        /// </summary>
        public static string Feedback_submitButton_Tap_No_comments {
            get {
                return ResourceManager.GetString("Feedback_submitButton_Tap_No_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate CycleStreets.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleStreets Customer Feedback .
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@cyclestreets.net.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Route.
        /// </summary>
        public static string FindRoute {
            get {
                return ResourceManager.GetString("FindRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred getting data from .
        /// </summary>
        public static string GetDataError {
            get {
                return ResourceManager.GetString("GetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journey facts.
        /// </summary>
        public static string JourneyFacts {
            get {
                return ResourceManager.GetString("JourneyFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey time.
        /// </summary>
        public static string JourneyTime {
            get {
                return ResourceManager.GetString("JourneyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kcal.
        /// </summary>
        public static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load route.
        /// </summary>
        public static string LoadRoute {
            get {
                return ResourceManager.GetString("LoadRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleStreets requires access to your location in order to provide navigation and mapping information. Do you want to allow this?.
        /// </summary>
        public static string LocationConsent {
            get {
                return ResourceManager.GetString("LocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Enabled.
        /// </summary>
        public static string LocationEnabled {
            get {
                return ResourceManager.GetString("LocationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable aerial view.
        /// </summary>
        public static string MainPage_ApplicationBarMenuItem_ToggleAerialView_Disable_aerial_view {
            get {
                return ResourceManager.GetString("MainPage_ApplicationBarMenuItem_ToggleAerialView_Disable_aerial_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable aerial view.
        /// </summary>
        public static string MainPage_ApplicationBarMenuItem_ToggleAerialView_Enable_aerial_view {
            get {
                return ResourceManager.GetString("MainPage_ApplicationBarMenuItem_ToggleAerialView_Enable_aerial_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string MainPage_OnNavigatedTo_Hello {
            get {
                return ResourceManager.GetString("MainPage_OnNavigatedTo_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string MainPage_OnNavigatedTo_Location {
            get {
                return ResourceManager.GetString("MainPage_OnNavigatedTo_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Style.
        /// </summary>
        public static string MapStyle {
            get {
                return ResourceManager.GetString("MapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} metres.
        /// </summary>
        public static string MetresShort {
            get {
                return ResourceManager.GetString("MetresShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cycling Speed.
        /// </summary>
        public static string MyCyclingSpeed {
            get {
                return ResourceManager.GetString("MyCyclingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Position.
        /// </summary>
        public static string MyPosition {
            get {
                return ResourceManager.GetString("MyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Route.
        /// </summary>
        public static string NoRoute {
            get {
                return ResourceManager.GetString("NoRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route found. Try another search.
        /// </summary>
        public static string NoRouteFoundTryAnotherSearch {
            get {
                return ResourceManager.GetString("NoRouteFoundTryAnotherSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suggestions.
        /// </summary>
        public static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite?.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite this save file with the current route?.
        /// </summary>
        public static string OverwriteMessage {
            get {
                return ResourceManager.GetString("OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we calculate your route..
        /// </summary>
        public static string PleaseWaitMsg {
            get {
                return ResourceManager.GetString("PleaseWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Sleep.
        /// </summary>
        public static string PreventSleep {
            get {
                return ResourceManager.GetString("PreventSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string Quiet {
            get {
                return ResourceManager.GetString("Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quietest route.
        /// </summary>
        public static string QuietestRoute {
            get {
                return ResourceManager.GetString("QuietestRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quietness.
        /// </summary>
        public static string Quietness {
            get {
                return ResourceManager.GetString("Quietness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quite Busy.
        /// </summary>
        public static string QuiteBusy {
            get {
                return ResourceManager.GetString("QuiteBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quite Quiet.
        /// </summary>
        public static string QuiteQuiet {
            get {
                return ResourceManager.GetString("QuiteQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying CycleStreets?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Number.
        /// </summary>
        public static string RouteNumber {
            get {
                return ResourceManager.GetString("RouteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse route data information from server. Please let us know about this error with the route you were trying to plan.
        /// </summary>
        public static string RouteParseError {
            get {
                return ResourceManager.GetString("RouteParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This route has been saved and can be loaded even when a data connection is unavailable from the Load Route menu..
        /// </summary>
        public static string RouteSaved {
            get {
                return ResourceManager.GetString("RouteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Saved.
        /// </summary>
        public static string RouteSavedTitle {
            get {
                return ResourceManager.GetString("RouteSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save route.
        /// </summary>
        public static string SaveRoute {
            get {
                return ResourceManager.GetString("SaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like us to guide you through how to use the app with a tutorial?.
        /// </summary>
        public static string ShowTutorialMsg {
            get {
                return ResourceManager.GetString("ShowTutorialMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signaled Crossings.
        /// </summary>
        public static string SignaledCrossings {
            get {
                return ResourceManager.GetString("SignaledCrossings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signaled Junctions.
        /// </summary>
        public static string SignaledJunctions {
            get {
                return ResourceManager.GetString("SignaledJunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your free trial has expired. Press OK to go to the store where you can download the full version of the app..
        /// </summary>
        public static string TrialExpiredMsg {
            get {
                return ResourceManager.GetString("TrialExpiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string TrialExpiredTitle {
            get {
                return ResourceManager.GetString("TrialExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing the CycleStreets trial. This trial lasts 72 hours and allows access to all the features of the full app. You can purchase the full version at any time from the app bar..
        /// </summary>
        public static string TrialWelcome {
            get {
                return ResourceManager.GetString("TrialWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Tap these boxes to close and continue&amp;#xA;&amp;#xA;You can add route markers in four ways. &amp;#xA;&amp;#xA;1. You can type in this box....
        /// </summary>
        public static string Tutorial1 {
            get {
                return ResourceManager.GetString("Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Tap this option to select your current position....
        /// </summary>
        public static string Tutorial2 {
            get {
                return ResourceManager.GetString("Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Tap this option to select the point on the map directly under the &amp;quot;+&amp;quot; cursor. You can drag the map around and pinch zoom to refine the position..
        /// </summary>
        public static string Tutorial3 {
            get {
                return ResourceManager.GetString("Tutorial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. You can tap anywhere on the map.
        /// </summary>
        public static string Tutorial4 {
            get {
                return ResourceManager.GetString("Tutorial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once there are at least two markers on the map you can tap this button to find your route..
        /// </summary>
        public static string Tutorial5 {
            get {
                return ResourceManager.GetString("Tutorial5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can remove a waypoint by tapping it..
        /// </summary>
        public static string Tutorial6 {
            get {
                return ResourceManager.GetString("Tutorial6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the route type with this drop down list. Change the default in the Settings menu.
        /// </summary>
        public static string Tutorial7 {
            get {
                return ResourceManager.GetString("Tutorial7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information button will open an additional menu with more information on your route..
        /// </summary>
        public static string Tutorial8 {
            get {
                return ResourceManager.GetString("Tutorial8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial Enabled.
        /// </summary>
        public static string TutorialEnabled {
            get {
                return ResourceManager.GetString("TutorialEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE LOCATION OR USE APP BAR.
        /// </summary>
        public static string TypeLocation {
            get {
                return ResourceManager.GetString("TypeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown street.
        /// </summary>
        public static string UnknownStreet {
            get {
                return ResourceManager.GetString("UnknownStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Busy.
        /// </summary>
        public static string VeryBusy {
            get {
                return ResourceManager.GetString("VeryBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} {1} onto {2}.
        /// </summary>
        public static string VoiceDescription {
            get {
                return ResourceManager.GetString("VoiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} you will reach your destination..
        /// </summary>
        public static string VoiceDescriptionEnd {
            get {
                return ResourceManager.GetString("VoiceDescriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at {0}.
        /// </summary>
        public static string VoiceDescriptionStart {
            get {
                return ResourceManager.GetString("VoiceDescriptionStart", resourceCulture);
            }
        }
    }
}
